using UnityEngine;
using System.Collections;
using System.Collections.Generic;


[RequireComponent(typeof(Steer))]
[RequireComponent(typeof(CharacterController))]


public class FlockerSteering : MonoBehaviour {

//movement variables - exposed in inspector panel
	private GameObject target  = null;
	
	//reference to an array of obstacles
	private  GameObject[] obstacles; 
	
	public GameObject main;
	//script object for GameManger
	private GameManager gm;

	
	public float gravity = 10000.0f; // keep us grounded

	public bool attack;
	
	// Each vehicle contains a CharacterController which helps to deal with
	// the relationship between movement initiated by the character and the forces
	// generated by contact with the terrain & other game objects.
	private CharacterController characterController;
	
	// the SteeringAttributes holds several variables needed for steering
	private SteeringAttributes attr;

	// the Steer component implements the basic steering functions
	private Steer steer;

	private Vector3 acceleration;	//change in velocity per second
	private Vector3 velocity;		//change in position per second
	public Vector3 Velocity {
		get { return velocity; }
		set { velocity = value;}
	}

	public GameObject Target {
		get { return target; }
		set { target = value;}
	}

	public bool Attack {
		get { return attack; }
		set { attack = value;}
	}

	void Start ()
	{
		acceleration = Vector3.zero;
		velocity = transform.forward;
		obstacles = GameObject.FindGameObjectsWithTag ("Obstacle");	
		
		//get component references
		characterController = gameObject.GetComponent<CharacterController> ();
		steer = gameObject.GetComponent<Steer> ();
	    main = GameObject.Find ("MainGO");
		attr = main.GetComponent<SteeringAttributes> ();
		gm = main.GetComponent<GameManager> ();
		attack = false;
	}
	
	void LateUpdate ()
	{
		CalcSteeringForce ();
		
		//update velocity
		velocity += acceleration * Time.deltaTime;
		velocity.y = 0;	// we are staying in the x/z plane
		velocity = Vector3.ClampMagnitude (velocity, attr.maxSpeed);
		
		//orient the transform to face where we going
		if (velocity != Vector3.zero)
			transform.forward = velocity.normalized;

		// keep us grounded
		velocity.y -= gravity * Time.deltaTime;

		// the CharacterController moves us subject to physical constraints
		characterController.Move (velocity * Time.deltaTime);
		
		//reset acceleration for next cycle
		acceleration = Vector3.zero;

	}
	
	
	//calculate and apply steering forces
	private void CalcSteeringForce ()
	{ 
		Vector3 force = Vector3.zero;
		
		
		//obstacles
		for (int i=0; i<obstacles.Length; i++) {	
			force += attr.avoidWt * steer.AvoidObstacle (obstacles [i], attr.avoidDist);
		}
		Debug.DrawRay (transform.position, force / 100.0f, Color.red);
		
		//force += attr.avoidWt * steer.AvoidObstacle (gm.centroidGO, attr.avoidDist);
	 
		//in bounds
		//force += attr.inBoundsWt * steer.StayInBounds (150, Vector3.zero);
		
		//seek target
		//force += attr.seekWt * steer.Seek (target.transform.position);
		
			///////////////////////////////////////////////////////MY CODE //////////////////////////////////////////////////////////
		
		//apply seperation force from GameManger's Flockers ArrayList
		//force += attr.seperationWt * steer.SeperationVer2(gm.GetFlockers()); //option #1
		if(attack == false)
		{
			force += attr.seperationWt * steer.Seperation(gm.GetFlockers()); //harder option #2
		
			//apply cohesion force from GameManger's Centroid 
			force += attr.cohesionWt * steer.Cohesion(gm.GetCentroid());
		
			//apply Alignment force from GameManger's Direction
			force += attr.allignWt * steer.Alignment(gm.GetDirection());
		}
		else
		{
			reachedTarget();
			force += attr.seekWt * steer.Seek(steer.FindClosestPrey(gm.GetPrey()).transform.position);
			force += attr.seperationWt * steer.Seperation(gm.GetFlockers()); //harder option #2
		}
			
		///////////////////////////////////////////////////////MY CODE //////////////////////////////////////////////////////////

		
		force = Vector3.ClampMagnitude (force, attr.maxForce);
		ApplyForce (force);
	}


	public void reachedTarget()
	{
		GameObject targ = steer.FindClosestPrey(gm.GetPrey());
		Vector3 tar = steer.FindClosestPrey(gm.GetPrey()).transform.position;
		float dist = Vector3.Distance(gameObject.transform.position, tar);
		if(dist  < 4)
		{
			attack = false;
			targ.transform.position = new Vector3(Random.Range(-200,200), 40, Random.Range(-200,200));
			Debug.Log("target reached");
			Camera.main.GetComponent<SmoothFollow> ().target = gm.GetCentGO().transform;
		}
	}

	private void ApplyForce (Vector3 steeringForce)
	{
		acceleration += steeringForce/attr.mass;
	}
}
